2024-08-04 22:43:22 [error] [UserService]: Error: User with Id: 100 not found
    at new ApiError (D:\1.LeapFrog\NODE\Budgeteer_\server\src\utils\ApiErrors.ts:8:14)
    at D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:80:19
    at step (D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:44:23)
    at Object.next (D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:25:53)
    at fulfilled (D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:16:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-08-04 22:45:08 [error] [UserService]: Error: User with Id: 100 not found
    at new ApiError (D:\1.LeapFrog\NODE\Budgeteer_\server\src\utils\ApiErrors.ts:8:14)
    at D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:80:19
    at step (D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:44:23)
    at Object.next (D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:25:53)
    at fulfilled (D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:16:58)
2024-08-04 22:48:33 [error] [UserService]: Error: User with Id: 100 not found
    at new ApiError (D:\1.LeapFrog\NODE\Budgeteer_\server\src\utils\ApiErrors.ts:8:14)
    at D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:80:19
    at step (D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:44:23)
    at Object.next (D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:25:53)
    at fulfilled (D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:16:58)
2024-08-04 22:51:43 [error] [UserService]: Error: "User with Id: 100 not found"
    at new ApiError (D:\1.LeapFrog\NODE\Budgeteer_\server\src\utils\ApiErrors.ts:8:14)
    at D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:80:19
    at step (D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:44:23)
    at Object.next (D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:25:53)
    at fulfilled (D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:16:58)
2024-08-04 22:52:42 [error] [UserService]: Error: User with Id: 100 not found
    at new ApiError (D:\1.LeapFrog\NODE\Budgeteer_\server\src\utils\ApiErrors.ts:8:14)
    at D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:80:19
    at step (D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:44:23)
    at Object.next (D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:25:53)
    at fulfilled (D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:16:58)
2024-08-04 22:56:05 [error] [UserService]: Error: User with Id: 100 not found
    at new ApiError (D:\1.LeapFrog\NODE\Budgeteer_\server\src\utils\ApiErrors.ts:8:14)
    at D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:80:19
    at step (D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:44:23)
    at Object.next (D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:25:53)
    at fulfilled (D:\1.LeapFrog\NODE\Budgeteer_\server\src\service\user.ts:16:58)
2024-08-04 23:25:13 [error] [ExpenseGroupService]: error: insert into "invites" ("group_id", "receiver_id", "sender_id") values ($1, DEFAULT, $2) - null value in column "receiver_id" of relation "invites" violates not-null constraint
    at Parser.parseErrorMessage (D:\1.LeapFrog\NODE\Budgeteer_\server\node_modules\pg-protocol\src\parser.ts:369:69)
    at Parser.handlePacket (D:\1.LeapFrog\NODE\Budgeteer_\server\node_modules\pg-protocol\src\parser.ts:188:21)
    at Parser.parse (D:\1.LeapFrog\NODE\Budgeteer_\server\node_modules\pg-protocol\src\parser.ts:103:30)
    at Socket.<anonymous> (D:\1.LeapFrog\NODE\Budgeteer_\server\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
2024-08-05 12:07:10 [error] [ExpenseGroupService]: error: insert into "invites" ("group_id", "receiver_id", "sender_id") values ($1, DEFAULT, $2) - null value in column "receiver_id" of relation "invites" violates not-null constraint
    at Parser.parseErrorMessage (D:\1.LeapFrog\NODE\Budgeteer_\server\node_modules\pg-protocol\src\parser.ts:369:69)
    at Parser.handlePacket (D:\1.LeapFrog\NODE\Budgeteer_\server\node_modules\pg-protocol\src\parser.ts:188:21)
    at Parser.parse (D:\1.LeapFrog\NODE\Budgeteer_\server\node_modules\pg-protocol\src\parser.ts:103:30)
    at Socket.<anonymous> (D:\1.LeapFrog\NODE\Budgeteer_\server\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
2024-08-05 12:07:29 [error] [ExpenseGroupService]: error: insert into "invites" ("group_id", "receiver_id", "sender_id") values ($1, DEFAULT, $2) - null value in column "receiver_id" of relation "invites" violates not-null constraint
    at Parser.parseErrorMessage (D:\1.LeapFrog\NODE\Budgeteer_\server\node_modules\pg-protocol\src\parser.ts:369:69)
    at Parser.handlePacket (D:\1.LeapFrog\NODE\Budgeteer_\server\node_modules\pg-protocol\src\parser.ts:188:21)
    at Parser.parse (D:\1.LeapFrog\NODE\Budgeteer_\server\node_modules\pg-protocol\src\parser.ts:103:30)
    at Socket.<anonymous> (D:\1.LeapFrog\NODE\Budgeteer_\server\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
2024-08-05 12:07:46 [error] [ExpenseGroupService]: error: insert into "invites" ("group_id", "receiver_id", "sender_id") values ($1, DEFAULT, $2) - null value in column "receiver_id" of relation "invites" violates not-null constraint
    at Parser.parseErrorMessage (D:\1.LeapFrog\NODE\Budgeteer_\server\node_modules\pg-protocol\src\parser.ts:369:69)
    at Parser.handlePacket (D:\1.LeapFrog\NODE\Budgeteer_\server\node_modules\pg-protocol\src\parser.ts:188:21)
    at Parser.parse (D:\1.LeapFrog\NODE\Budgeteer_\server\node_modules\pg-protocol\src\parser.ts:103:30)
    at Socket.<anonymous> (D:\1.LeapFrog\NODE\Budgeteer_\server\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
2024-08-05 12:07:47 [error] [ExpenseGroupService]: error: insert into "invites" ("group_id", "receiver_id", "sender_id") values ($1, DEFAULT, $2) - null value in column "receiver_id" of relation "invites" violates not-null constraint
    at Parser.parseErrorMessage (D:\1.LeapFrog\NODE\Budgeteer_\server\node_modules\pg-protocol\src\parser.ts:369:69)
    at Parser.handlePacket (D:\1.LeapFrog\NODE\Budgeteer_\server\node_modules\pg-protocol\src\parser.ts:188:21)
    at Parser.parse (D:\1.LeapFrog\NODE\Budgeteer_\server\node_modules\pg-protocol\src\parser.ts:103:30)
    at Socket.<anonymous> (D:\1.LeapFrog\NODE\Budgeteer_\server\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
